name: idz
description: IDz app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cross_file: ^0.3.3+8
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  flutter_form_builder: ^9.1.0
  flutter_platform_alert: ^0.4.0
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.1.1
  form_builder_validators: ^9.0.0
  get: ^4.6.6
  google_fonts: ^4.0.4
  image_picker: ^1.0.7
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  keyboard_dismisser: ^3.0.0
  local_auth: ^2.3.0
  mime: ^1.0.4
  path: ^1.8.2
  path_provider: ^2.1.2
  photo_view: ^0.14.0
  reorderable_grid_view: ^2.2.8
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.4

dev_dependencies:
  analyzer: ^5.13.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  # generate: true // 多言語時にtrue
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansJP-Thin.ttf
          weight: 100
